/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPartiesRouteImport } from './routes/_authenticated/parties'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments.index'
import { Route as AuthenticatedJournalIndexRouteImport } from './routes/_authenticated/journal.index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsCurrenciesRouteImport } from './routes/_authenticated/settings.currencies'
import { Route as AuthenticatedSettingsBranchesRouteImport } from './routes/_authenticated/settings.branches'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated/settings.audit'
import { Route as AuthenticatedSalesNewRouteImport } from './routes/_authenticated/sales.new'
import { Route as AuthenticatedReportsTrialBalanceRouteImport } from './routes/_authenticated/reports.trial-balance'
import { Route as AuthenticatedReportsStatementsRouteImport } from './routes/_authenticated/reports.statements'
import { Route as AuthenticatedReportsGeneralLedgerRouteImport } from './routes/_authenticated/reports.general-ledger'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedPaymentsNewRouteImport } from './routes/_authenticated/payments.new'
import { Route as AuthenticatedJournalNewRouteImport } from './routes/_authenticated/journal.new'
import { Route as AuthenticatedJournalIdRouteImport } from './routes/_authenticated/journal.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartiesRoute = AuthenticatedPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalIndexRoute =
  AuthenticatedJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCurrenciesRoute =
  AuthenticatedSettingsCurrenciesRouteImport.update({
    id: '/settings/currencies',
    path: '/settings/currencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBranchesRoute =
  AuthenticatedSettingsBranchesRouteImport.update({
    id: '/settings/branches',
    path: '/settings/branches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/settings/audit',
    path: '/settings/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesNewRoute = AuthenticatedSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsTrialBalanceRoute =
  AuthenticatedReportsTrialBalanceRouteImport.update({
    id: '/reports/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsStatementsRoute =
  AuthenticatedReportsStatementsRouteImport.update({
    id: '/reports/statements',
    path: '/reports/statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsGeneralLedgerRoute =
  AuthenticatedReportsGeneralLedgerRouteImport.update({
    id: '/reports/general-ledger',
    path: '/reports/general-ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/purchases/new',
    path: '/purchases/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsNewRoute =
  AuthenticatedPaymentsNewRouteImport.update({
    id: '/payments/new',
    path: '/payments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalNewRoute = AuthenticatedJournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalIdRoute = AuthenticatedJournalIdRouteImport.update({
  id: '/journal/$id',
  path: '/journal/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/items': typeof AuthenticatedItemsRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/parties': typeof AuthenticatedPartiesRoute
  '/journal/$id': typeof AuthenticatedJournalIdRoute
  '/journal/new': typeof AuthenticatedJournalNewRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/reports/general-ledger': typeof AuthenticatedReportsGeneralLedgerRoute
  '/reports/statements': typeof AuthenticatedReportsStatementsRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/journal/': typeof AuthenticatedJournalIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/items': typeof AuthenticatedItemsRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/parties': typeof AuthenticatedPartiesRoute
  '/journal/$id': typeof AuthenticatedJournalIdRoute
  '/journal/new': typeof AuthenticatedJournalNewRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/reports/general-ledger': typeof AuthenticatedReportsGeneralLedgerRoute
  '/reports/statements': typeof AuthenticatedReportsStatementsRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/journal': typeof AuthenticatedJournalIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/items': typeof AuthenticatedItemsRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/parties': typeof AuthenticatedPartiesRoute
  '/_authenticated/journal/$id': typeof AuthenticatedJournalIdRoute
  '/_authenticated/journal/new': typeof AuthenticatedJournalNewRoute
  '/_authenticated/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/reports/general-ledger': typeof AuthenticatedReportsGeneralLedgerRoute
  '/_authenticated/reports/statements': typeof AuthenticatedReportsStatementsRoute
  '/_authenticated/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/_authenticated/sales/new': typeof AuthenticatedSalesNewRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/_authenticated/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/journal/': typeof AuthenticatedJournalIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/dashboard'
    | '/items'
    | '/ledger'
    | '/parties'
    | '/journal/$id'
    | '/journal/new'
    | '/payments/new'
    | '/purchases/new'
    | '/reports/general-ledger'
    | '/reports/statements'
    | '/reports/trial-balance'
    | '/sales/new'
    | '/settings/audit'
    | '/settings/branches'
    | '/settings/currencies'
    | '/settings/users'
    | '/journal/'
    | '/payments/'
    | '/purchases/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounts'
    | '/dashboard'
    | '/items'
    | '/ledger'
    | '/parties'
    | '/journal/$id'
    | '/journal/new'
    | '/payments/new'
    | '/purchases/new'
    | '/reports/general-ledger'
    | '/reports/statements'
    | '/reports/trial-balance'
    | '/sales/new'
    | '/settings/audit'
    | '/settings/branches'
    | '/settings/currencies'
    | '/settings/users'
    | '/journal'
    | '/payments'
    | '/purchases'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/items'
    | '/_authenticated/ledger'
    | '/_authenticated/parties'
    | '/_authenticated/journal/$id'
    | '/_authenticated/journal/new'
    | '/_authenticated/payments/new'
    | '/_authenticated/purchases/new'
    | '/_authenticated/reports/general-ledger'
    | '/_authenticated/reports/statements'
    | '/_authenticated/reports/trial-balance'
    | '/_authenticated/sales/new'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/branches'
    | '/_authenticated/settings/currencies'
    | '/_authenticated/settings/users'
    | '/_authenticated/journal/'
    | '/_authenticated/payments/'
    | '/_authenticated/purchases/'
    | '/_authenticated/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parties': {
      id: '/_authenticated/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AuthenticatedPartiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal/': {
      id: '/_authenticated/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AuthenticatedJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/currencies': {
      id: '/_authenticated/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof AuthenticatedSettingsCurrenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/branches': {
      id: '/_authenticated/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof AuthenticatedSettingsBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/new': {
      id: '/_authenticated/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthenticatedSalesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/trial-balance': {
      id: '/_authenticated/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/statements': {
      id: '/_authenticated/reports/statements'
      path: '/reports/statements'
      fullPath: '/reports/statements'
      preLoaderRoute: typeof AuthenticatedReportsStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/general-ledger': {
      id: '/_authenticated/reports/general-ledger'
      path: '/reports/general-ledger'
      fullPath: '/reports/general-ledger'
      preLoaderRoute: typeof AuthenticatedReportsGeneralLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/new': {
      id: '/_authenticated/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AuthenticatedPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal/new': {
      id: '/_authenticated/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof AuthenticatedJournalNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal/$id': {
      id: '/_authenticated/journal/$id'
      path: '/journal/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof AuthenticatedJournalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedPartiesRoute: typeof AuthenticatedPartiesRoute
  AuthenticatedJournalIdRoute: typeof AuthenticatedJournalIdRoute
  AuthenticatedJournalNewRoute: typeof AuthenticatedJournalNewRoute
  AuthenticatedPaymentsNewRoute: typeof AuthenticatedPaymentsNewRoute
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedReportsGeneralLedgerRoute: typeof AuthenticatedReportsGeneralLedgerRoute
  AuthenticatedReportsStatementsRoute: typeof AuthenticatedReportsStatementsRoute
  AuthenticatedReportsTrialBalanceRoute: typeof AuthenticatedReportsTrialBalanceRoute
  AuthenticatedSalesNewRoute: typeof AuthenticatedSalesNewRoute
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsBranchesRoute: typeof AuthenticatedSettingsBranchesRoute
  AuthenticatedSettingsCurrenciesRoute: typeof AuthenticatedSettingsCurrenciesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedJournalIndexRoute: typeof AuthenticatedJournalIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedItemsRoute: AuthenticatedItemsRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedPartiesRoute: AuthenticatedPartiesRoute,
  AuthenticatedJournalIdRoute: AuthenticatedJournalIdRoute,
  AuthenticatedJournalNewRoute: AuthenticatedJournalNewRoute,
  AuthenticatedPaymentsNewRoute: AuthenticatedPaymentsNewRoute,
  AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  AuthenticatedReportsGeneralLedgerRoute:
    AuthenticatedReportsGeneralLedgerRoute,
  AuthenticatedReportsStatementsRoute: AuthenticatedReportsStatementsRoute,
  AuthenticatedReportsTrialBalanceRoute: AuthenticatedReportsTrialBalanceRoute,
  AuthenticatedSalesNewRoute: AuthenticatedSalesNewRoute,
  AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
  AuthenticatedSettingsBranchesRoute: AuthenticatedSettingsBranchesRoute,
  AuthenticatedSettingsCurrenciesRoute: AuthenticatedSettingsCurrenciesRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedJournalIndexRoute: AuthenticatedJournalIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
